/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LanguageSelector: typeof import('./../src/components/Selectors/LanguageSelector/LanguageSelector.vue')['default']
    Page: typeof import('./../src/components/Layout/Page/Page.vue')['default']
    PageSuspense: typeof import('./../src/components/PageSuspense.vue')['default']
    PSABanner: typeof import('./../src/components/Layout/PSABanner/PSABanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
