/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogPost: typeof import('./../src/components/BlogPost.vue')['default']
    LanguageSelector: typeof import('./../src/components/Selectors/LanguageSelector/LanguageSelector.vue')['default']
    Page: typeof import('./../src/components/Layout/Page/Page.vue')['default']
    PageSuspense: typeof import('./../src/components/PageSuspense.vue')['default']
    PSABanner: typeof import('./../src/components/Layout/PSABanner/PSABanner.vue')['default']
    ResponsiveImage: typeof import('./../src/components/Layout/ResponsiveImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const BlogPost: typeof import('./../src/components/BlogPost.vue')['default']
  const LanguageSelector: typeof import('./../src/components/Selectors/LanguageSelector/LanguageSelector.vue')['default']
  const Page: typeof import('./../src/components/Layout/Page/Page.vue')['default']
  const PageSuspense: typeof import('./../src/components/PageSuspense.vue')['default']
  const PSABanner: typeof import('./../src/components/Layout/PSABanner/PSABanner.vue')['default']
  const ResponsiveImage: typeof import('./../src/components/Layout/ResponsiveImage.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}